Merge to Development PR
samgaco/battleship pull request #1
Opened 2019-11-22 16:41 UTC by wathigo

## Tasks Completed
1. Creation of player, game board, and ship factories.
2. Implementation of the tests for the factories.
3. Implementation of dome tasks.

Please review our PR. Thank you.

2019-11-22 19:53 UTC, azdrenymeri requested changes
## Hello @wathigo  and @samgaco 👋 
### You did a great job 👍 
You have been using `module.exports` and `require` in some of your `js` files.
Kindly change that and use the ES6 `import/export`.
To be able to use `import/export` with `Jest` you need to install babel which you already did
but `.babelrc` file is missing on your project so kindly add it and check this [Link](https://stackoverflow.com/a/49656707/6539808) for further instructions.
### Kindly implement the changes and add it for a re-review

2019-11-22 19:53 UTC, azdrenymeri commented on package.json
> +    "start": "webpack-dev-server --mode development --open"
Your run commands should go under the `scripts`

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/ship.js
> +module.exports = newShip;
Use `export` instead of `module.exports`

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/player.js
> +module.exports = player;
Same here use(the ES6) `export` instead

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/gameBoard.js
> +module.exports = gameBoard;
Same as `ship.js` and `player.js` use `export`

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/player.js
> +module.exports = player;
Same here use `export`

2019-11-22 19:53 UTC, azdrenymeri commented on src/tests/gameBoard.test.js
> +const newShip = require('../factories/ship');
Use  `import` instead of `require`

2019-11-22 19:53 UTC, azdrenymeri commented on src/tests/ship.test.js
> +const newShip = require('../factories/ship');
Same here use `import` instead of `require`

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/gameBoard.js
> +  shipsSunk() {
A more shorter and concise way(ES6 Way) is using high-order functions
`return this.ships.filter(ship => ship.isSunk() === true).length`

2019-11-22 19:53 UTC, azdrenymeri commented on src/factories/player.js
> +module.exports = player;
Same here

2019-11-23 10:55 UTC, JamesOkunlade approved these changes
# Approved 🙂 

### Great job on this project and nice job implementing the corrections requested by the previous reviewer.

It's 👍 for me. Go ahead and merge. 

Good luck with your next project.

**James Okunlade**
Happy coding! 😎

2019-11-23 11:02 UTC, merged